# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1404964580);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1404964700);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1404989540);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1404986060);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/hiruma");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140608211810");
user_pref("browser.slowStartup.averageTime", 4042);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140608211810");
user_pref("browser.startup.homepage_override.mstone", "30.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":4,\"passwords\":4}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1404206756542");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1404964283443");
user_pref("datareporting.policy.firstRunTime", "1404120356541");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 3912);
user_pref("datareporting.sessions.current.main", 368);
user_pref("datareporting.sessions.current.sessionRestored", 3658);
user_pref("datareporting.sessions.current.startTime", "1404995637424");
user_pref("datareporting.sessions.current.totalTime", 15);
user_pref("datareporting.sessions.currentIndex", 18);
user_pref("datareporting.sessions.previous.13", "{\"s\":1404483740187,\"a\":12,\"t\":78,\"c\":false,\"m\":628,\"fp\":5456,\"sr\":4568}");
user_pref("datareporting.sessions.previous.14", "{\"s\":1404714716675,\"a\":57,\"t\":16863,\"c\":true,\"m\":679,\"fp\":5603,\"sr\":4820}");
user_pref("datareporting.sessions.previous.15", "{\"s\":1404731595476,\"a\":0,\"t\":6,\"c\":false,\"m\":401,\"fp\":4995,\"sr\":4553}");
user_pref("datareporting.sessions.previous.16", "{\"s\":1404964217745,\"a\":38,\"t\":26018,\"c\":true,\"m\":717,\"fp\":5538,\"sr\":4701}");
user_pref("datareporting.sessions.previous.17", "{\"s\":1404991911888,\"a\":3,\"t\":43,\"c\":true,\"m\":342,\"fp\":4401,\"sr\":4076}");
user_pref("datareporting.sessions.prunedIndex", 12);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"30.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-ja@firefox.mozilla.org\":{\"version\":\"30.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ja@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"30.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:30.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140319.01");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1404118604000,\"rdfTime\":1375741724000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1402265219000},\"langpack-ja@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ja@firefox.mozilla.org.xpi\",\"mtime\":1402265258000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1402265219000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1404118448000,\"rdfTime\":1402264008000}}}]");
user_pref("extensions.lastAppVersion", "30.0");
user_pref("extensions.lastPlatformVersion", "30.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140608211810");
user_pref("gecko.mstone", "30.0");
user_pref("idle.lastDailyNotification", 1404964303);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1404714797);
user_pref("places.history.expiration.transient_current_max_pages", 52800);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1404714797);
user_pref("toolkit.startup.last_success", 1404995637);
user_pref("toolkit.telemetry.previousBuildID", "20140608211810");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1406689285);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
