# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9499b63dd3ee32a78820c841fe829bf9d97ca199fe25e50543153bd4096668007b46edf92e8c7effa08d24e464406c48b4769caa54eedefd76dd44a4421e1dad

test:
  secret_key_base: 178ffdd0bab2a5a4ddbcd9d429b72c286e86a186723c95a8447b5f2d1bd3c022038a84e815670837933786adc8b398bf5b626b5f6a2144010266fa738bf06ae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
