# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.migration.version", 6);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.startup.homepage_override.buildID", "20120423122624");
user_pref("browser.startup.homepage_override.mstone", "rv:12.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.enabledAddons", "langpack-en-GB@firefox.mozilla.org:12.0,langpack-ja@firefox.mozilla.org:12.0,globalmenu@ubuntu.com:3.2.3,langpack-en-ZA@firefox.mozilla.org:12.0,ubufox@ubuntu.com:2.0.2,{972ce4c6-7e08-4474-a285-3208198ce6fd}:12.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1335809911000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1335198007000},\"langpack-ja@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-ja@firefox.mozilla.org.xpi\",\"mtime\":1335198014000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/globalmenu@ubuntu.com\",\"mtime\":1335809849000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1335198007000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1335809849000}}}]");
user_pref("extensions.lastAppVersion", "12.0");
user_pref("extensions.lastPlatformVersion", "12.0");
user_pref("extensions.pendingOperations", false);
user_pref("places.history.expiration.transient_current_max_pages", 52801);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
